name: update-readme

on: [push]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Check Python version
        run:  python --version
      - name: Install requirements.txt
        run: pip install -r ./requirements.txt
      - name: Run update_posts.py script
        run: python ./scripts/update_posts.py ${{ secrets.API_POSTS_ENDPOINT }}
      - name: Commit and push changes
        run: |
          git config --global user.name "${{ secrets.GIT_USER }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"

          git add -A
          git commit -m "updated README.md"
          git push
      - name: Generate artifact
        uses: actions/upload-artifact@v2
        with:
          name: readme-artifact
          path: README.md
  bump-backend:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Check Python version
        run:  python --version
      - name: Install requirements.txt
        run: pip install -r ./requirements.txt
      - name: Run bump_backend.py script
        run: python ./scripts/bump_backend.py ${{ secrets.API_BUMP_ENDPOINT }}
